name: Generate terraform docs

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  contents: write  # required for pushing changes
  id-token: write  # useful for OIDC if needed

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: true
          git-commit-message: "chore(docs): update terraform docs"
