name: Creating Variable
on:
  workflow_dispatch

env:
  cloud: aws
jobs:
  greeting_job:
     runs-on: ubuntu-latest
     env: 
       name1: dev
     steps:
       - name: show Data
         run: echo " $name1 is use $cloud cloud ${{ PRESENT}}        
