name: Secret Variable
on:
  workflow_dispatch

env:
  cloud: aws
jobs:
  greeting_job:
     runs-on: self-hosted
     env: 
       name: dev
     steps:
       - name: show Data   
         run: echo "$name is using $cloud cloud and this ${{ secrets.MY_SCERET}} secret ."
