name: inputs Variables try 

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "Enter one nummber"
        required: true
        default: '0'
    
      number2:
        description: "Enter Second number"
        required: true
        default: '0'
        

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo " ${{ github.event.inputs.number1}} and ${{ github.event.inputs.number2}}! "
    - name: add numbers
      run: | 
         num1=${{ github.event.inputs.number1 }}
         num2=${{ github.event.inputs.number2 }}
         sum= $((num1 + num2))
         echo "$num1 + $num2 = $sum"
