name: inputs Variables try 

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "Enter one nummber"
        required: true
        default: '0'
    
      number2:
        description: "Enter Second number"
        required: true
        default: '0'
        

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo " ${{ github.event.inputs.number1}} and ${{ github.event.inputs.number2}}! "
    - name: add numbers
      run: echo " Sum = ((${{ github.event.inputs.number1 }} + ${{ github.event.inputs.number2 }})) ! " 
         
