name : Variable
on:
  workflow_dispatch
env:
  cloud: aws
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
       greeting:  DEV
    steps:
      - name: Run a one-line script
        run: echo "$greeting using $cloud cloud!"
